### Creating a new Product
POST {{host}}/product
Content-Type: application/json

{
  "name": "Teste de Http",
  "price": 25.99
}

### Getting a Product
GET {{host}}/product/d96183b2-45f5-4565-915f-6fdced9d9383

### Enabling a Product
GET {{host}}/product/d96183b2-45f5-4565-915f-6fdced9d9383/enable

### Disabling a Product
GET {{host}}/product/d96183b2-45f5-4565-915f-6fdced9d9383/disable
